CREATE TABLE IF NOT EXISTS bookkeeping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR  NOT NULL,
    summary FLOAT NOT NULL,
    quantity INT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL DEFAULT ""
)   